/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

import { SanityImageSource } from '@sanity/image-url';
import { PortableTextBlock } from 'next-sanity';

export interface Post {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;

	title: string;
	featured: boolean;
	slug: {
		_type: 'slug';
		current: string;
	};
	publishedAt: string;
	blogThumbnail: SanityImageSource;
	author: string;
	tag?: string;
	subtitle?: string;

	embedding: number[];

	body: PortableTextBlock[];
}
